import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'

const read = path => readFileSync(new URL(path, import.meta.url), 'utf8')
const landing = read('../src/views/Landing.jsx')
const landingCss = read('../src/views/Landing.css')
const entryCss = read('../src/views/LandingUpdatesEntry.css')
const updatesPage = read('../src/components/LandingUpdatesPage.jsx')
const updatesPageCss = read('../src/components/LandingUpdatesPage.css')
const entryGroup = read('../src/components/EntryButtonGroup.jsx')
const entrySurface = read('../src/components/EntryButtonSurface.jsx')
const entrySurfaceCss = read('../src/components/EntryButtonSurface.css')

describe('Landing updates entry', () => {
  it('starts Landing title and entries from mount state without arrows or hover navigation', () => {
    expect(landing).not.toContain('LandingEntryArrow')
    expect(landing).not.toContain('NewToneHandLines')
    expect(landing).not.toContain('onPointerEnter')
    expect(landing).not.toContain('onWheel')
    expect(landing).not.toContain('onTouchMove')
    expect(landingCss).not.toContain('landing-guide-arrow')
    expect(landingCss).not.toContain('landing-title:hover')
    expect(landing).toContain('window.requestAnimationFrame(() => { begin() })')
    expect(landing).toContain('landingLeaveRetractStartedRef')
    expect(landing).toContain("retract({ duration: reducedMotion || motionMode === 'reduced' ? 0 : undefined })")
  })

  it('keeps Updates and Reader entries in one shared click group', () => {
    expect(landing).toContain("import EntryButtonGroup from '../components/EntryButtonGroup'")
    expect(landing).toContain('groupId="landing-entries"')
    expect(landing).toContain("id: 'updates'")
    expect(landing).toContain('id: readerEntryId')
    expect(landing).toContain("materialMode: 'background'")
    expect(landing).toContain("materialMode: hasProgress ? 'world' : 'background'")
    expect(entryCss).toContain('.landing-entry-button-group {')
    expect(entryCss).toContain('position: absolute')
    expect(entryCss).toContain('top: calc(100% + 3.6rem)')
    expect(entryCss).toContain('left: 50%')
    expect(entryCss).toContain('display: flex')
    expect(entryCss).toContain('flex-direction: row')
    expect(entryCss).toContain('flex-wrap: nowrap')
    expect(entryCss).not.toContain('top: calc(100% + 8rem)')
    expect(entryCss).not.toContain('landing-direction-prompts')
    expect(entryCss).not.toContain('enter-labels')
    expect(entryCss).not.toContain('return-labels')
  })

  it('keeps Updates navigation click-only and completion-driven', () => {
    expect(updatesPage).toContain('entryId="landing-updates-return"')
    expect(updatesPage).toContain('visible={interactive}')
    expect(updatesPage).toContain('onActionComplete={handleReturnComplete}')
    expect(updatesPage).toContain("recordRuntimeAudit('updates-return-intent'")
    expect(updatesPage).not.toContain('LandingEntryArrow')
    expect(updatesPage).not.toContain('resolveTouchReturnSwipe')
    expect(updatesPage).not.toContain('addEventListener')
    expect(updatesPageCss).not.toContain('return-ring')
    expect(updatesPageCss).not.toContain('touch-action: none')
  })

  it('keeps geometry, fill, text and action completion in the shared surface', () => {
    expect(entrySurface).toContain('<button')
    expect(entrySurface).toContain('type="button"')
    expect(entrySurface).toContain('data-entry-id={entryId}')
    expect(entrySurface).toContain('data-entry-layer-model="shared-svg-geometry>text"')
    expect(entrySurface).toContain('onActionCompleteRef.current?.')
    expect(entrySurface).toContain('data-entry-fill-progress={progress.fill.toFixed(3)}')
    expect(entryGroup).toContain("const GROUP_PHASE = Object.freeze({ VISIBLE: 'visible', EXITING: 'exiting' })")
    expect(entryGroup).toContain('visible={visible && phase !== GROUP_PHASE.EXITING}')
    expect(entryGroup).toContain('onActionStartRef.current?.({ entryId, inputType })')
    expect(entryGroup).toContain('onActionStart={handleActionStart}')
    expect(entryGroup).toContain('onActionComplete={handleActionComplete}')
    expect(entryGroup).toContain("recordRuntimeAudit('entry-group-click'")
    expect(entryGroup).toContain("recordRuntimeAudit('entry-group-action-complete'")
    expect(entrySurfaceCss).toContain('.shared-entry-control')
    expect(entrySurfaceCss).toContain('.shared-entry-material')
    expect(entrySurfaceCss).toContain('.shared-entry-frame')
  })
})
