import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'

const read = path => readFileSync(new URL(path, import.meta.url), 'utf8')
const page = read('../src/components/LandingUpdatesPage.jsx')
const entry = read('../src/components/landing/LandingUpdatesReturnEntry.jsx')
const flow = read('../src/landing/landingUpdatesReturnFlow.js')
const styles = read('../src/components/LandingUpdatesPage.css')
const scramble = read('../src/components/ScrambleText.jsx')
const scrambleHook = read('../src/hooks/useScrambleText.js')

describe('Landing updates return entry', () => {
  it('uses the Landing paper and exposes a local desktop return state machine', () => {
    expect(styles).toContain('background-color: var(--reader-paper, var(--paper-base));')
    expect(page).toContain('data-return-state={returnFlow.state}')
    expect(page).toContain('className="landing-updates-page__return-backdrop"')
    expect(page).toContain('<LandingUpdatesReturnEntry')
    expect(entry).toContain('className="landing-updates-return-trigger"')
    expect(page).toContain('onPointerLeave={handlePointerLeave}')
    expect(page).toContain('useReducer')
  })

  it('proves the strict text, arrow, ready order without a rendered ring', () => {
    expect(flow).toContain("TEXT_REVEAL: 'text'")
    expect(flow).toContain("ARROW_REVEAL: 'arrow'")
    expect(flow).toContain("ARROW_TURN: 'arrow-turn'")
    expect(flow).toContain("READY: 'ready'")
    expect(flow).toContain("WITHDRAW_ARROW_TURN: 'withdraw-arrow-turn'")
    expect(flow).toContain("WITHDRAW_ARROW: 'withdraw-arrow'")
    expect(flow).toContain("WITHDRAW_TEXT: 'withdraw-text'")
    expect(page).toContain('UPDATES_RETURN_EVENT.TEXT_REVEALED')
    expect(page).toContain('UPDATES_RETURN_EVENT.ARROW_READY')
    expect(page).toContain('UPDATES_RETURN_EVENT.ARROW_TURNED')
    expect(entry).toContain('showRing={false}')
    expect(styles).toContain('updates-return-arrow-reveal')
    expect(styles).toContain('updates-return-arrow-withdraw')
    expect(styles).toContain('[data-return-state="withdraw-arrow"]')
    expect(styles).toContain('[data-return-state="arrow-turn"] .landing-updates-return__arrow .landing-entry-arrow__rotator')
    expect(styles).toContain('transform: rotate(-180deg)')
    expect(styles).toContain('[data-return-state="ready"] .landing-updates-return__arrow .landing-entry-arrow__rotator')
  })

  it('uses one withdrawal path for leave, wheel, and outside pointer input', () => {
    expect(page).toContain('UPDATES_RETURN_EVENT.WHEEL_RETURN')
    expect(page).toContain('returnTriggerRef.current?.contains(event.target)')
    expect(page).toContain("window.addEventListener('wheel', onWheel, { passive: false })")
    expect(page).toContain("window.addEventListener('pointerdown', onGlobalPointerDown, { capture: true, passive: true })")
    expect(page).toContain('reason: UPDATES_RETURN_REASON.WHEEL')
    expect(page).toContain('deltaY: event.deltaY')
    expect(page).toContain("returnToLanding: true")
    expect(page).toContain("reason: UPDATES_RETURN_REASON.LEAVE")
    expect(page).toContain("reason: UPDATES_RETURN_REASON.OUTSIDE")
    expect(page).toContain('navigationIssuedRef')
    expect(page).not.toContain('setTimeout')
    expect(styles).toContain('withdraw-arrow')
    expect(styles).toContain('withdraw-text')
    expect(styles).toContain('transition: none !important')
    expect(styles).toContain('transition-duration: 360ms')
    expect(styles).toContain('animation: updates-return-arrow-withdraw')
    expect(scramble).toContain('withdrawing = false')
    expect(scramble).toContain('onWithdrawn')
    expect(scrambleHook).toContain('onWithdrawnRef.current?.()')
    expect(scrambleHook).toContain('onRevealedRef.current?.()')
  })

  it('keeps the one-shot navigation guard through the return surface phase', () => {
    expect(page).toContain('if (phase === UPDATES_PHASE.LANDING)')
    expect(page).toContain('navigationIssuedRef.current = false')
    expect(page).toContain('if (!interactive)')
    expect(page.indexOf('if (phase === UPDATES_PHASE.LANDING)'))
      .toBeLessThan(page.indexOf('if (!interactive)'))
  })

  it('uses a soft gradient backdrop and explicit leave/wheel timing', () => {
    expect(styles).toContain('linear-gradient(')
    expect(styles).toContain('rgba(32, 29, 25, 0) 100%')
    expect(styles).toContain('backdrop-filter: blur(6px)')
    expect(styles).toContain('transition: opacity 640ms ease-in 80ms')
    expect(styles).toContain('transition-duration: 480ms')
    expect(flow).toContain("effect: 'withdraw-start'")
    expect(flow).toContain("effect: flow.returnToLanding ? 'navigation-ready' : null")
  })

  it('keeps the existing mobile touch path separate from the desktop state', () => {
    expect(flow).toContain('armed: false')
    expect(flow).toContain("effect: 'armed'")
    expect(page).toContain('resolveUpdatesTouchIntent')
    expect(page).toContain('resolveUpdatesWheelIntent')
    expect(page).toContain('UPDATES_RETURN_EVENT.MOBILE_TAP')
    expect(page).toContain('UPDATES_RETURN_EVENT.SWIPE_CANCEL')
    expect(entry).toContain('onPointerDown={onPointerDown}')
    expect(styles).toContain('@media (pointer: coarse)')
    expect(styles).toContain('pointer-events: auto;')
    expect(styles).toContain('touch-action: pan-y;')
    expect(styles).toContain('[data-return-state="ready"] .landing-updates-return')
  })
})
