import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'

const read = path => readFileSync(new URL(path, import.meta.url), 'utf8')
const selector = read('../src/components/LanguageWheelSelector.jsx')
const styles = read('../src/components/LanguageWheelSelector.css')
const hook = read('../src/hooks/useScrambleText.js')
const transition = read('../src/components/ReadingTransition.jsx')
const transitionStyles = read('../src/components/ReadingTransition.css')

describe('language wheel selector stage', () => {
  it('uses the shared path fill for reveal and keeps language commit after snap', () => {
    expect(selector).toContain("data-language-selector-phase={phase}")
    expect(selector).toContain("recordRuntimeAudit('language-fill-open-start'")
    expect(selector).toContain("recordRuntimeAudit('language-fill-open-complete'")
    expect(selector).toContain("recordRuntimeAudit('language-fill-close-start'")
    expect(selector).toContain("recordRuntimeAudit('language-fill-close-complete'")
    expect(selector).toContain("import EntryButtonFrame, { useEntryFrameProgress } from './EntryButtonFrame'")
    expect(selector).toContain('className="shared-entry-control language-wheel-selector"')
    expect(selector).toContain('data-language-fill="shared-path"')
    expect(selector).toContain('data-entry-paint-model="shared-path-fill>shared-path-stroke>text"')
    expect(selector).toContain('fillProgress={coverProgress}')
    expect(selector).toContain('fillDirection={fillDirection}')
    expect(selector).toContain('onClick={handleClick}')
    expect(selector).toContain('onPointerEnter={handlePointerEnter}')
    expect(selector).toContain('onPointerLeave={handlePointerLeave}')
    expect(selector).toContain('onWheel={handleWheel}')
    expect(selector).toContain("window.addEventListener('pointermove'")
    expect(selector).toContain("window.addEventListener('pointerup'")
    expect(selector).not.toContain('setPointerCapture')
    expect(selector).toContain('suppressClickRef')
    expect(selector).toContain('data-entry-frame-progress={frameProgress.toFixed(3)}')
    expect(selector).toContain('data-language-drag-offset={dragOffset.toFixed(1)}')
    expect(selector).toContain("recordRuntimeAudit('language-wheel-language-committed'")
    expect(selector).toContain("recordRuntimeAudit('language-wheel-transition-complete'")
    expect(selector).toContain('onLanguageChangeRef.current?.(completedTrack.target)')
    expect(selector.indexOf("recordRuntimeAudit('language-wheel-transition-complete'"))
      .toBeLessThan(selector.indexOf('onLanguageChangeRef.current?.(completedTrack.target)'))
  })

  it('uses a shared frame, desktop wheel track, and mobile continuous drag track', () => {
    expect(selector).toContain('language-wheel-selector__viewport')
    expect(selector).toContain('language-wheel-selector__track')
    expect(selector).toContain('onTransitionEnd={handleTrackTransitionEnd}')
    expect(selector).toContain('data-language-track-state={trackClass}')
    expect(selector).toContain("recordRuntimeAudit('language-wheel-drag-start'")
    expect(selector).toContain("recordRuntimeAudit('language-wheel-drag-move'")
    expect(selector).toContain("recordRuntimeAudit('language-wheel-drag-end'")
    expect(selector).toContain('data-language-candidates={coarse ? \'vertical\' : \'none\'}')
    expect(selector).toContain("recordRuntimeAudit('language-arrow-reveal-start'")
    expect(selector).toContain("recordRuntimeAudit('language-arrow-revealed'")
    expect(selector).toContain('data-language-arrow-state={arrowState}')
    expect(styles).not.toContain('border: 1px solid')
    expect(styles).toContain('overflow: hidden')
    expect(styles).toContain('transform: translate3d(0, calc(-33.333333% + var(--language-drag-offset, 0px)), 0)')
    expect(styles).toContain("data-language-track-state='next'")
    expect(styles).toContain("data-language-track-state='previous'")
    expect(styles).toContain("data-language-arrow-state='visible'")
    expect(styles).toContain('transition: opacity 260ms ease')
    expect(styles).toContain('@media (pointer: fine)')
    expect(styles).toContain('@media (pointer: coarse)')
    expect(styles).toContain('touch-action: none')
  })

  it('does not use text decoding for the language selector', () => {
    expect(selector).not.toContain('useScrambleText')
    expect(selector).not.toContain('language-preview-start')
    expect(selector).not.toContain('language-preview-ready')
    expect(hook).toContain('charInterval = 70')
    expect(hook).toContain('scrambleInterval = 40')
    expect(hook).toContain('partialScramble')
    expect(hook).not.toContain('duration = 800')
    expect(transition).toContain('charInterval: titleCharInterval')
    expect(transition).toContain('scrambleInterval: 50')
    expect(transitionStyles).not.toContain('tube-startup')
  })
})
