import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'

const read = path => readFileSync(new URL(path, import.meta.url), 'utf8')
const selector = read('../src/components/LanguageWheelSelector.jsx')
const styles = read('../src/components/LanguageWheelSelector.css')
const hook = read('../src/hooks/useScrambleText.js')
const transition = read('../src/components/ReadingTransition.jsx')
const transitionStyles = read('../src/components/ReadingTransition.css')

describe('language wheel selector stage', () => {
  it('keeps browser-language decoding separate from confirmation', () => {
    expect(selector).toContain("data-language-selector-phase={phase}")
    expect(selector).toContain("recordRuntimeAudit('language-preview-start'")
    expect(selector).toContain("recordRuntimeAudit('language-preview-ready'")
    expect(selector).toContain('data-language-fill="none"')
    expect(selector).toContain("import EntryButtonFrame from './EntryButtonFrame'")
    expect(selector).toContain('className="shared-entry-control language-wheel-selector"')
    expect(selector).toContain('data-entry-frame-fill="disabled"')
    expect(selector).toContain('onClick={handleClick}')
    expect(selector).toContain('onPointerEnter={handlePointerEnter}')
    expect(selector).toContain('onWheel={handleWheel}')
    expect(selector).toContain('onPointerUp={handlePointerUp}')
    expect(selector).toContain("recordRuntimeAudit('language-wheel-language-committed'")
    expect(selector).toContain('enabled: phase === \'decoding\'')
  })

  it('uses a framed clipped viewport and a real three-slot track', () => {
    expect(selector).toContain('language-wheel-selector__viewport')
    expect(selector).toContain('language-wheel-selector__track')
    expect(selector).toContain('onTransitionEnd={handleTrackTransitionEnd}')
    expect(selector).toContain('data-language-track-state={trackClass}')
    expect(selector).toContain("recordRuntimeAudit('language-wheel-transition-start'")
    expect(selector).toContain("recordRuntimeAudit('language-wheel-transition-complete'")
    expect(selector).toContain('LANGUAGE_ARROW_DELAY_MS')
    expect(selector).toContain("recordRuntimeAudit('language-arrow-reveal-start'")
    expect(selector).toContain("recordRuntimeAudit('language-arrow-revealed'")
    expect(selector).toContain('data-language-arrow-state={arrowState}')
    expect(styles).not.toContain('border: 1px solid')
    expect(styles).toContain('overflow: hidden')
    expect(styles).toContain('transform: translate3d(0, -33.333333%, 0)')
    expect(styles).toContain("data-language-track-state='next'")
    expect(styles).toContain("data-language-track-state='previous'")
    expect(styles).toContain('@keyframes language-wheel-current-blink')
    expect(styles).toContain("data-language-arrow-state='visible'")
    expect(styles).toContain('transition: opacity 260ms ease')
    expect(styles).not.toContain("data-language-arrow-state='floating'")
    expect(styles).not.toContain('language-wheel-selector__candidate')
  })

  it('uses one fixed-duration animation clock instead of text-length intervals', () => {
    expect(hook).toContain('duration = 800')
    expect(hook).toContain('requestAnimationFrame')
    expect(hook).toContain('Math.floor(progress * units.length)')
    expect(hook).toContain('createScrambleBuffer')
    expect(hook).toContain('resolveScrambleBuffer')
    expect(hook).not.toContain('partialScramble')
    expect(hook).not.toContain('charInterval')
    expect(hook).not.toContain('scrambleInterval')
    expect(transition).toContain('duration: modeStage ? 900 : 1800')
    expect(transitionStyles).not.toContain('tube-startup')
  })
})
