import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'

const read = path => readFileSync(new URL(path, import.meta.url), 'utf8')
const selector = read('../src/components/LanguageWheelSelector.jsx')
const styles = read('../src/components/LanguageWheelSelector.css')
const hook = read('../src/hooks/useScrambleText.js')
const transition = read('../src/components/ReadingTransition.jsx')
const transitionStyles = read('../src/components/ReadingTransition.css')

describe('language wheel selector stage', () => {
  it('uses the shared path fill for reveal and keeps language commit after continue', () => {
    expect(selector).toContain("data-language-selector-phase={phase}")
    expect(selector).toContain("recordRuntimeAudit('language-fill-open-start'")
    expect(selector).toContain("recordRuntimeAudit('language-fill-open-complete'")
    expect(selector).toContain("recordRuntimeAudit('language-fill-close-start'")
    expect(selector).toContain("recordRuntimeAudit('language-fill-close-complete'")
    expect(selector).toContain("import EntryButtonFrame from './EntryButtonFrame'")
    expect(selector).toContain("import { ENTRY_BUTTON_TIMINGS, createEntryProgress, useEntryButtonTimeline } from './entryButtonTimeline'")
    expect(selector).not.toContain('LANGUAGE_ENTRY_TIMINGS')
    expect(selector).not.toContain('const runSequence')
    expect(selector).toContain('className="shared-entry-control language-wheel-selector"')
    expect(selector).toContain('data-language-fill="shared-path"')
    expect(selector).toContain('data-entry-paint-model="shared-path-fill>shared-path-stroke>text"')
    expect(selector).toContain('fillProgress={progress.fill}')
    expect(selector).toContain('fillDirection={fillDirection}')
    expect(selector).toContain('onClick={handleClick}')
    expect(selector).toContain('onPointerEnter={handlePointerEnter}')
    expect(selector).toContain('onPointerLeave={handlePointerLeave}')
    expect(selector).toContain('onWheel={handleWheel}')
    expect(selector).toContain("window.addEventListener('pointermove'")
    expect(selector).toContain("window.addEventListener('pointerup'")
    expect(selector).not.toContain('setPointerCapture')
    expect(selector).toContain('suppressClickRef')
    expect(selector).toContain('data-entry-frame-progress={progress.frame.toFixed(3)}')
    expect(selector).toContain('data-language-drag-offset={dragOffset.toFixed(1)}')
    expect(selector).toContain("data-language-panel-state={panelMode}")
    expect(selector).toContain("startPanelTransition('opening', () =>")
    expect(selector).toContain("startPanelTransition('closing'")
    expect(selector).toContain('handlePanelTransitionEnd')
    expect(selector).toContain('currentLanguageLabel')
    expect(selector).toContain("recordRuntimeAudit('language-entry-exit-start'")
    expect(selector).toContain("recordRuntimeAudit('language-entry-exit-complete'")
    expect(selector).toContain("recordRuntimeAudit('language-arrow-dismissed'")
    expect(selector).toContain("setTrackMotion('reset')")
    expect(selector).toContain("setTrackMotion('idle')")
    expect(selector).toContain("recordRuntimeAudit('language-wheel-language-previewed'")
    expect(selector).toContain("recordRuntimeAudit('language-wheel-transition-complete'")
    expect(selector).toContain('onLanguagePreviewRef.current?.(completedTrack.target)')
    expect(selector).toContain("centerTrack('preview')")
    expect(selector).toContain('LANGUAGE_ARROW_DELAY_MS = 180')
    expect(selector).toContain('revealArrowAfterText()')
    expect(selector).toContain('const initialSteps = [')
    expect(selector).toContain("if (coarse) initialSteps.push({ key: 'fill', to: 1, duration: ENTRY_BUTTON_TIMINGS.fillOpen })")
    expect(selector).toContain("startPanelTransition('opening', () =>")
    expect(selector).toContain("runTimeline([{ key: 'fill', to: 1, duration: ENTRY_BUTTON_TIMINGS.fillOpen }]")
    expect(selector).toContain("runTimeline([{ key: 'fill', to: 0, duration: ENTRY_BUTTON_TIMINGS.fillClose }]")
    expect(selector).not.toContain('closeTextCompleteRef')
    expect(selector).not.toContain('closePanelCompleteRef')
    expect(selector.indexOf("startPanelTransition('opening', () =>"))
      .toBeLessThan(selector.indexOf("runTimeline([{ key: 'fill', to: 1, duration: ENTRY_BUTTON_TIMINGS.fillOpen }]") )
    const openingFillIndex = selector.indexOf("runTimeline([{ key: 'fill', to: 1, duration: ENTRY_BUTTON_TIMINGS.fillOpen }]")
    expect(selector.indexOf("setSelectorPhase('ready')", openingFillIndex))
      .toBeGreaterThan(openingFillIndex)
    expect(selector.indexOf("recordRuntimeAudit('language-wheel-transition-complete'"))
      .toBeLessThan(selector.indexOf('onLanguagePreviewRef.current?.(completedTrack.target)'))
    expect(selector).not.toContain('animateCover(0')
    expect(selector).toContain('onLanguagePreview')
  })

  it('uses a shared frame, desktop wheel track, and mobile continuous drag track', () => {
    expect(selector).toContain('language-wheel-selector__viewport')
    expect(selector).toContain('language-wheel-selector__track')
    expect(selector).toContain('onTransitionEnd={handleTrackTransitionEnd}')
    expect(selector).toContain('data-language-track-state={trackClass}')
    expect(selector).toContain('data-language-track-motion={trackMotion}')
    expect(selector).not.toContain('language-wheel-selector__placeholder')
    expect(selector).toContain("recordRuntimeAudit('language-wheel-drag-start'")
    expect(selector).toContain("recordRuntimeAudit('language-wheel-drag-move'")
    expect(selector).toContain("recordRuntimeAudit('language-wheel-drag-end'")
    expect(selector).toContain('data-language-candidates={coarse ? \'vertical\' : \'none\'}')
    expect(selector).toContain("recordRuntimeAudit('language-arrow-reveal-start'")
    expect(selector).toContain("recordRuntimeAudit('language-arrow-revealed'")
    expect(selector).toContain('data-language-arrow-state={arrowState}')
    expect(styles).not.toContain('border: 1px solid')
    expect(styles).toContain('overflow: hidden')
    expect(styles).toContain('.language-wheel-selector__panel-track')
    expect(styles).toContain('position: relative')
    expect(styles).toContain('position: absolute')
    expect(styles).toContain('top: 0')
    expect(styles).toContain('left: 0')
    expect(styles).toContain("data-language-panel-state='opening'")
    expect(styles).toContain("data-language-panel-state='closing'")
    expect(styles).toContain("data-language-panel-state='idle'")
    expect(styles).toContain('z-index: 1')
    expect(styles).toContain('z-index: 2')
    expect(styles).toContain('transform: translate3d(0, calc(-33.333333% + var(--language-drag-offset, 0px)), 0)')
    expect(styles).toContain("data-language-track-motion='reset'")
    expect(styles).toContain('transition: none')
    expect(styles).toContain("data-language-track-state='next'")
    expect(styles).toContain("data-language-track-state='previous'")
    expect(styles).toContain("data-language-arrow-state='visible'")
    expect(styles).toContain('transition: opacity 260ms ease')
    expect(styles).toContain('@media (pointer: fine)')
    expect(styles).toContain('@media (pointer: coarse)')
    expect(styles).toContain('touch-action: none')
    expect(styles).toContain('font-size: inherit')
  })

  it('does not use text decoding for the language selector', () => {
    expect(selector).not.toContain('useScrambleText')
    expect(selector).not.toContain('language-preview-start')
    expect(selector).not.toContain('language-preview-ready')
    expect(hook).toContain('charInterval = 70')
    expect(hook).toContain('scrambleInterval = 40')
    expect(hook).toContain('partialScramble')
    expect(hook).not.toContain('duration = 800')
    expect(transition).toContain('charInterval: titleCharInterval')
    expect(transition).toContain('scrambleInterval: 50')
    expect(transitionStyles).not.toContain('tube-startup')
  })
})
