import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { getPageSceneTrail } from '../src/components/reader/ReaderTraceProgress'
import { isReaderContentEndVisible, isReaderViewportAtBottom } from '../src/components/reader/ReaderBeatStack'

const read = path => readFileSync(new URL(path, import.meta.url), 'utf8')
const landing = read('../src/views/Landing.jsx')
const landingCss = read('../src/views/Landing.css')
const landingGuideCss = read('../src/views/LandingGuideArrow.css')
const reader = read('../src/views/ReaderOrchestrator.jsx')
const stage = read('../src/views/ReaderStage.jsx')
const stageCss = read('../src/views/ReaderStage.css')
const contractCss = read('../src/views/ReaderShellContract.css')
const progress = read('../src/components/reader/ReaderTraceProgress.jsx')
const transition = read('../src/components/ReadingTransition.jsx')
const transitionCss = read('../src/components/ReadingTransition.css')
const transitionHoverCss = read('../src/components/ReadingTransitionHover.css')
const app = read('../src/App.jsx')
const transitionStore = read('../src/stores/transitionStore.js')
const copy = read('../src/i18n/copy.js')
const returnControl = read('../src/components/reader/ReaderReturnControl.jsx')
const returnControlCss = read('../src/components/reader/ReaderReturnControl.css')
const updatesPage = read('../src/components/LandingUpdatesPage.jsx')
const updatesPageCss = read('../src/components/LandingUpdatesPage.css')
const readingEntryController = read('../src/transitions/readingEntryController.js')
const beatStack = read('../src/components/reader/ReaderBeatStack.jsx')

describe('Reader shell contract boundaries', () => {
  it('does not restore the rejected mode-stage environmental divider', () => {
    expect(transitionCss).not.toContain(".language-init[data-selector-stage='mode']::before")
  })

  it('removes Center triggers and debug controls from Landing and Reader', () => {
    expect(landing).not.toContain("transitionTo('center'")
    expect(landing).not.toContain('enterCenter')
    expect(landing).not.toContain('landing-reset')
    expect(reader).not.toContain("transitionTo('center'")
    expect(stage).not.toContain('ReaderEnvironmentControl')
  })

  it('keeps environment layers mounted for mode fades but visually removes them from Standard', () => {
    expect(stage).toContain('<ReaderPrecipitation />')
    expect(stage).toContain('<ReaderTraceProgress')
    expect(stage).not.toContain("readingMode === 'standard' && <ReaderTraceProgress")
    expect(contractCss).toContain('.reader-stage-page--standard .reader-environment-light')
    expect(contractCss).toContain('opacity:0 !important')
    expect(contractCss).toContain('background-color 1600ms')
    expect(stageCss).toContain('.reader-stage-page--standard .reader-stage-beat')
    expect(stageCss).toContain('animation: none !important')
  })

  it('keeps the full Reader shell mounted when no publication exists', () => {
    expect(reader).toContain('readerContent.length === 0')
    expect(reader).toContain('<EmptyReaderOrchestrator')
    expect(reader).toContain('<ReaderStage')
    expect(stage).toContain('emptyDocument')
    expect(stage).toContain('<ReaderTools')
    expect(stage).toContain('returnVisible = emptyDocument ||')
    expect(stage).toContain('暂无可读页面')
    expect(stage).toContain('!emptyDocument && <ReaderTraceProgress')
  })

  it('uses current-page reading progress without a pointer tooltip', () => {
    expect(progress).toContain('getPageSceneTrail(beats, focusBeatIndex)')
    expect(stage).toContain('progress={progress}')
    expect(progress).not.toContain('pointedPercentage')
    expect(progress).not.toContain('linearIndex')
    expect(progress).not.toContain('readerContentIndex')
    expect(progress).not.toContain('onClick=')
    expect(progress).toContain("language === 'en' ? 'remaining:' : '剩余：'")
    expect(progress).toContain('reader-reading-percent-label')
    expect(progress).toContain('reader-reading-percent-value')
    expect(progress).toContain('Math.round((1 - visualProgress) * 100)')
    expect(progress).toContain('{visualRemaining}%')
    expect(progress).not.toContain('100 - percentage')
    expect(progress).not.toContain('is-hovered')
    expect(progress).not.toContain('onPointerMove=')
    expect(progress).not.toContain("window.addEventListener('pointermove', trackHover)")
    expect(progress).not.toContain('tabIndex=')
    expect(contractCss).toContain('pointer-events:none; touch-action:pan-y')
    expect(contractCss).toContain('top:clamp(18px,calc(var(--reader-visual-progress) * 100%)')
    expect(contractCss).toContain('left:16.5px;')
    expect(contractCss).toContain('transform:translate(-50%,-100%)')
    expect(contractCss).toContain('left:14.5px;')
    expect(contractCss).toContain('.reader-reading-percent-label { writing-mode:vertical-rl; text-orientation:upright; }')
    expect(contractCss).toContain('.reader-reading-percent-value { writing-mode:horizontal-tb;')
    expect(contractCss).toContain('display:inline-flex; flex-direction:column; align-items:center; gap:2px;')
    expect(contractCss).toContain('.reader-stage-page .reader-trace { width:108px;')
    expect(contractCss).toContain('.reader-stage-page .reader-trace { left:8px; width:100px; }')
    expect(stageCss).toContain('writing-mode: vertical-rl')
    expect(progress).toContain('visualProgress')
    expect(progress).toContain('Math.exp(-delta / 1900)')
    expect(contractCss).toContain('var(--reader-feather-start)')
    expect(contractCss).toContain('var(--reader-feather-end)')
    expect(contractCss).toContain('repeating-linear-gradient')
    expect(contractCss).not.toContain('[data-progress="0"]')
    expect(contractCss).toMatch(/\.reader-trace-line > \.reader-trace-base,[\s\S]*?inset:0 auto 0 0;[\s\S]*?height:auto;/)
    expect(contractCss).toContain('.reader-trace.is-complete .reader-trace-line { opacity:1; }')
    expect(stage.match(/<ReaderTraceProgress/g)).toHaveLength(1)
  })

  it('keeps Landing prompts complete and selection circles retractable', () => {
    expect(copy).toContain("landingPromptInitial: '向下滚动 · 开始读取'")
    expect(copy).toContain("landingPromptResume: '向下滚动 · 继续读取'")
    expect(copy).toContain("landingPromptInitial: 'Scroll down to begin'")
    expect(transition).toContain('primaryHold.retract()')
    expect(transition).toContain('targetRef.current = 0')
    expect(transition).toContain('data-selector-stage={currentStage.id}')
    expect(transition).toContain('language-btn--primary')
    expect(transition).toContain('language-btn--secondary')
    expect(transition).toContain('lang-hover-bridge')
    expect(transition).toContain('lang-expand-layer')
    expect(transition).toContain('className="ritual-entry-arrow ritual-entry-arrow--primary"')
    expect(transition).toContain('className="ritual-entry-arrow ritual-entry-arrow--secondary"')
    expect(transition).toContain('className="ritual-entry-arrow ritual-entry-arrow--language"')
    expect(transition).toContain('sourceRef={primaryTextRef}')
    expect(transition).toContain('sourceRef={currentLanguageLabelRef}')
    expect(transition).toContain('showRing={false}')
    expect(transition).not.toContain('RitualHandAffordance')
    expect(transition).not.toContain('LanguageExpandAffordance')
    expect(transition).toContain('const alternateLanguage = languageSlots.find(code => code !== language)')
    expect(transition).toContain('READER_LANGUAGES.find(item => item.code !== language)?.code')
    expect(transition).toContain('!modeStage && (expanded || languageLabelPinned)')
    expect(transition).not.toContain('const row1 = languageSlots')
    expect(transitionCss).toContain('@keyframes language-current-ring-draw')
    expect(transitionCss).toContain('@keyframes language-note-arrow-draw')
    expect(transitionCss).toContain('transition: opacity 360ms ease, translate 520ms')
    expect(transitionCss).toContain('left: calc(50% + 80px)')
    expect(transition).toContain('onEntryStart={() => setAlternateLanguageReady(true)}')
    expect(transition).not.toContain('reading-transition-direction')
    expect(transitionHoverCss).toContain('.ritual-hand-affordance--ring-only')
    expect(transitionHoverCss).toContain('@keyframes ritual-entry-ring-draw')
    expect(transitionHoverCss).toContain('@keyframes ritual-entry-arrow-bob')
    expect(transitionHoverCss).toContain("[data-ritual-ready='true'] .ritual-hand-affordance__arrow")
    expect(transitionHoverCss).not.toContain('ritual-hand-affordance__line')
    expect(transitionHoverCss).toContain('left: calc(100% + 5px)')
    expect(transitionHoverCss).toContain('width: 32px')
    expect(transitionHoverCss).toContain('ritual-entry-ring-draw 2200ms')
    expect(transitionHoverCss).toContain('stroke-dashoffset 1200ms')
    expect(app).toContain('[data-selector-option][data-ritual-armed="true"]')
    expect(transition).toContain('if (!armedOption || locked) return undefined')
    expect(readingEntryController).toContain('FIRST_LANDING_LEAVE_MS: 1600')
    expect(readingEntryController).toContain('RETURN_LANDING_LEAVE_MS: 1600')
    expect(readingEntryController).toContain('LANG_LEAVING_MS: 1600')
    expect(readingEntryController).toContain('MODE_LEAVING_MS: 1600')
    expect(readingEntryController).toContain('export const REDUCED_READING_ENTRY_TIMINGS')
    expect(readingEntryController).toContain("motionMode === 'reduced'")
    expect(readingEntryController).toContain("'(prefers-reduced-motion: reduce)'")
    expect(app).toContain('useReadingEntry(motionMode)')
    expect(landingCss).toContain('calc(var(--landing-leave-ms, 1600ms) - 360ms) ease-in 360ms')
    expect(transitionCss).toContain('transition-delay: 1250ms')
    expect(transitionCss).toContain('ritual-options-release 1600ms')
    expect(transitionCss).toContain('animation-delay: 0ms !important')
    expect(transitionCss).toContain('transition-delay: 0ms !important')
    expect(landingCss).toContain('.page-shell[data-motion-mode="reduced"] .landing')
    expect(transition).not.toContain('文本层已接入')
  })

  it('draws one compact fixed-pivot Landing guide and rotates it in place', () => {
    expect(landing).toContain('className="landing-title-n-host"')
    expect(landing).toContain('className="landing-guide-entry-arrow"')
    expect(landingGuideCss).toContain('left: 0')
    expect(landingGuideCss).toContain('top: 50%')
    expect(landingGuideCss).toContain('transform-origin: 0 35px')
    expect(landingGuideCss).toContain('transform-box: view-box')
    expect(landingGuideCss).toContain('.landing-entry-arrow--left')
    expect(landingGuideCss).toContain('.landing-entry-arrow--down')
  })

  it('runs Reader return entirely inside the live Landing instead of handing between two logos', () => {
    expect(transitionStore).toContain("targetView === 'landing' && preset === 'reader-to-surface'")
    expect(transitionStore).toContain("landingArrivalKind: 'return'")
    expect(transitionStore).toContain('return commitTargetView(targetView, preset, payload)')
    expect(landing).toContain("landingArrivalKind === 'return'")
    expect(landing).toContain('const RETURN_TITLE_DRAW_MS = 1450')
    expect(landing).toContain('const RETURN_STATUS_BLINK_COUNT = 2')
    expect(landing).toContain('const RETURN_STATUS_FADE_MS = 260')
    expect(landing).toContain('const RETURN_GUIDE_DELAY_MS = 1600')
    expect(landing).toContain('begin({ duration: drawDuration, markIntroComplete: false })')
    expect(landing).toContain('setReturnStatusFading(true)')
    expect(landing).toContain('setReturnStatusVisible(false)')
    expect(landing).toContain('await retract(')
    expect(landing).toContain('landing-return-status__text')
    expect(landing).toContain('!returnSequenceActive && <NewToneHandLines />')
    expect(landingGuideCss).toContain('@keyframes landing-return-status-fade')
    expect(landing).not.toContain('showSignatureLines')
    expect(landing.match(/<NewToneHandLines \/>/g)).toHaveLength(1)
    expect(app).not.toContain('readerReturnHandoffActive')
    expect(landing).not.toContain('landing--return-handoff')
    expect(landingCss).not.toContain('.landing--return-handoff')
  })

  it('offers the return choice at the real page end and at the final node on direct-input devices', () => {
    expect(isReaderViewportAtBottom(500, 500, 1008)).toBe(true)
    expect(isReaderViewportAtBottom(480, 500, 1008)).toBe(false)
    expect(stage).toContain('const DIRECT_READER_QUERY')
    expect(stage).toContain('const returnVisible = emptyDocument || readerAtBottom || (directReaderInput && finalNodeReached)')
    expect(stage).toContain('onViewportBoundaryChange={handleViewportBoundaryChange}')
    expect(beatStack).toContain('lastBeat.getBoundingClientRect().bottom <= viewport.getBoundingClientRect().bottom')
    expect(stage).not.toContain('escapeReturnVisible')
    expect(stage).toContain('returnVisible && <ReaderReturnControl')
    expect(returnControl).toContain("'(hover: hover) and (pointer: fine)'")
    expect(returnControl).toContain("event.pointerType === 'mouse' && hasHoverPointer()) onArm()")
    expect(returnControl).toContain("!entryReady && event.pointerType === 'mouse' && hasHoverPointer()) onDisarm()")
    expect(returnControl).toContain("isDirectPointer(event.pointerType) && !armed")
    expect(returnControl).toContain('event.detail === 0 && !armed')
    expect(stage).toContain('onDisarm={() => updateReturnArmed(false)}')
    expect(returnControl).toContain('if (!visualArmed) return undefined')
    expect(returnControl).toContain('event.deltaY > RETURN_WHEEL_THRESHOLD')
    expect(returnControl).toContain('data-return-progress={progress.toFixed(3)}')
    expect(returnControl).toContain("window.addEventListener('wheel', onWheel, { passive: true })")
    expect(returnControl).toContain("window.addEventListener('pointermove', onPointerMove, { passive: true })")
    expect(returnControl).not.toContain("window.addEventListener('touchmove'")
    expect(returnControl).not.toContain('setTimeout')
    expect(returnControl).not.toContain('preventDefault')
    expect(returnControl).not.toContain('stopPropagation')
    expect(returnControl).toContain('<button')
    expect(beatStack).toContain('if (returnArmed || !atBottomRef.current')
    expect(returnControlCss).toContain('z-index: 12')
    expect(returnControlCss).toContain('bottom: max(104px')
    expect(returnControlCss).toContain('bottom: max(72px')
    expect(copy).toContain("returnToLanding: '返回入口'")
    expect(copy).toContain("returnToLanding: 'Return to entrance'")
    expect(copy).not.toContain("returnToLanding: 'return to main screen'")
  })

  it('retracts the return affordance before confirmed navigation instead of hiding it in one frame', () => {
    expect(returnControl).toContain('const RETURN_RING_RETRACT_MS = 1200')
    expect(returnControl).toContain('const target = visualArmed ? 1 : 0')
    expect(returnControl).toContain('pendingCompleteRef.current = true')
    expect(returnControl).toContain('textExitCompleteRef.current')
    expect(returnControl).toContain('arrowExitCompleteRef.current')
    expect(returnControl).toContain('maybeCompleteReturn')
    expect(returnControl).toContain('returnTextStable')
    expect(returnControl).toContain('setCompleting(true)')
    expect(returnControl).toContain('handleTextExitComplete')
    expect(returnControl).toContain('handleArrowExitComplete')
    expect(returnControl).toContain('const affordanceVisible = visualArmed || progress > 0.001')
    expect(returnControl).toContain("visualArmed ? ' is-armed' : ''")
    expect(returnControlCss).toContain('.reader-return-control.has-affordance .reader-return-affordance__ring')
    expect(returnControlCss).toContain('[data-return-ready="true"] .reader-return-affordance__arrow')
    expect(returnControlCss).toContain('@keyframes reader-return-arrow-bob')
    expect(returnControlCss).toContain('transition: opacity 360ms ease')
    expect(returnControl).toContain('const RETURN_RING_DRAW_MS = 2200')
    expect(returnControl).toContain('}, [visualArmed])')
    expect(returnControl).toContain('}, [entryReady, maybeCompleteReturn, visualArmed])')
    expect(returnControl).toContain('reader-return-entry-arrow')
    expect(returnControl).toContain('onExitComplete={handleArrowExitComplete}')
    expect(returnControlCss).toContain('left: calc(100% + 4px)')
    expect(returnControlCss).toContain('width: 32px')
  })

  it('arms the mobile updates return once and routes the next explicit upward swipe', () => {
    expect(updatesPage).toContain('if (!mobileReturnArmed) setMobileReturnArmed(true)')
    expect(updatesPage).toContain('if (!interactive || !mobileReturnReady) return undefined')
    expect(updatesPage).toContain('resolveTouchReturnSwipe({')
    expect(updatesPage).toContain("window.addEventListener('pointermove', onPointerMove, { passive: false })")
    expect(updatesPage).not.toContain("action === 'return'")
    expect(updatesPageCss).toContain('updates-return-ring-draw 2200ms')
    expect(updatesPageCss).toContain('.landing-updates-page[data-return-ready="true"]')
    expect(updatesPageCss).toContain('touch-action: none')
  })

  it('shows the mobile return choice when real content ends, without waiting for the scroll spacer', () => {
    expect(isReaderContentEndVisible(800, 808)).toBe(true)
    expect(isReaderContentEndVisible(800, 820)).toBe(false)
    expect(beatStack).toContain('? isReaderContentEndVisible(viewport.getBoundingClientRect().bottom, lastBeat.getBoundingClientRect().bottom)')
    expect(beatStack).toContain('isReaderContentEndVisible(viewportRect.bottom, lastBeat.getBoundingClientRect().bottom)')
    expect(beatStack).toContain(': lastNodeReached && lastBeat.getBoundingClientRect().bottom')
  })

  it('reveals one measured return arrow after the label settles without a circle', () => {
    expect(returnControl).toContain('LandingEntryArrow')
    expect(returnControl).toContain('sourceRef={returnTextRef}')
    expect(returnControl).toContain('entryReady={returnTextStable}')
    expect(returnControl).toContain('data-return-ready={entryReady')
    expect(returnControl).not.toContain('reader-return-affordance__ring')
    expect(returnControl).not.toContain('reader-return-affordance__arrow')
  })

  it('keeps stable scene IDs available without rendering left-side scene icons', () => {
    const beats = [
      { worldState: { locationId: 'inner-street' } },
      { worldState: { locationId: 'inner-street' } },
      { worldState: { locationId: 'inner-commercial-street' } },
    ]
    const trail = getPageSceneTrail(beats, 1)
    expect(trail).toEqual([
      { locationId: 'inner-street', firstBeatIndex: 0, lastBeatIndex: 1, state: 'current' },
      { locationId: 'inner-commercial-street', firstBeatIndex: 2, lastBeatIndex: 2, state: 'future' },
    ])
    expect(progress).not.toContain('<ReaderSceneGlyph')
    expect(progress).not.toContain('className={`reader-scene-footprint')
    expect(contractCss).not.toContain('.reader-stage-page .reader-scene-footprint')
    expect(contractCss).toContain('left:14px')
  })
})
