import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'

const read = path => readFileSync(new URL(path, import.meta.url), 'utf8')
const control = read('../src/components/reader/ReaderReturnControl.jsx')
const surface = read('../src/components/EntryButtonSurface.jsx')
const frame = read('../src/components/EntryButtonFrame.jsx')
const surfaceCss = read('../src/components/EntryButtonSurface.css')
const stage = read('../src/views/ReaderStage.jsx')

describe('portable Reader return control', () => {
  it('is a thin host wrapper around the shared click timeline', () => {
    expect(control).toContain('visible = false')
    expect(control).toContain('mobile = false')
    expect(control).toContain("worldLayer = 'surface'")
    expect(control).toContain('onReturnStart')
    expect(control).toContain('onReturnComplete')
    expect(control).toContain('<EntryButtonSurface')
    expect(control).toContain('entryId="reader-return"')
    expect(control).not.toContain('LandingEntryArrow')
    expect(control).not.toContain('setTimeout')
  })

  it('owns one shared SVG geometry for frame, fill, and text', () => {
    expect(surface).toContain('<EntryButtonFrame')
    expect(frame).toContain("const FILL_DIRECTIONS = ['left', 'right', 'top', 'bottom', 'center']")
    expect(frame).toContain('const FRAME_ORIGINS')
    expect(frame).toContain('const FRAME_PATHS')
    expect(frame).toContain('function materialTransform(direction, progress)')
    expect(frame).toContain('data-entry-paint-model="shared-path-fill>shared-path-stroke"')
    expect(frame).not.toContain('getFillRect')
    expect(frame).not.toContain('<rect')
    expect(frame).toContain('<clipPath id={fillClipId}')
    expect(frame).toContain('href={`#${shapeId}`}')
    expect(frame).toContain('clipPath={`url(#${fillClipId})`}')
    expect(surface).toContain('data-return-fill-direction')
    expect(surface).toContain('data-return-frame-origin')
    expect(surface).toContain('data-return-layer-model')
    expect(surfaceCss).toContain('.shared-entry-frame')
    expect(surfaceCss).toContain('.shared-entry-material')
    expect(surfaceCss).toContain('color-mix(')
    expect(surfaceCss).toContain('var(--return-fill-progress)')
    expect(surface).not.toContain("color: fillActive ? 'var(--return-text-active)'")
  })

  it('keeps boundary progress in the shared control while ReaderStage owns callbacks', () => {
    expect(control).toContain('forwardRef')
    expect(control).toContain('setBoundaryProgress')
    expect(control).toContain('controlledProgress={alwaysVisible ? 0 : boundaryProgress}')
    expect(surface).toContain('controlledProgress = null')
    expect(surface).toContain('boundaryFactor')
    expect(stage).toContain('sceneBoundaryControlRef={returnControlRef}')
    expect(stage).toContain('alwaysVisible={emptyDocument || finalReaderBeat}')
    expect(stage).toContain('onReturnStart={onReturnStart}')
    expect(stage).toContain('onReturnComplete={onReturnLanding}')
    expect(stage).not.toContain('readerReturnFlow')
    expect(stage).not.toContain('READER_RETURN_')
  })
})
