import { expect, test, type Locator } from '@playwright/test'
async function sampleRoll(track: Locator, progress: number) {
  return track.evaluate((element, progress) => {
    const motion = element.getAnimations().find(animation => (animation as CSSTransition).transitionProperty === 'transform')
    if (!motion?.effect) throw new Error('Expected whole-group transform motion')
    motion.pause()
    const duration = Number(motion.effect.getTiming().duration)
    motion.currentTime = duration * progress
    const old = element.querySelector('.scene-mainline-storefront__label-text')!.getBoundingClientRect()
    const incoming = element.querySelector('.scene-mainline-storefront__replacement')!.getBoundingClientRect()
    return { duration, old: { left: old.left, right: old.right }, incoming: { left: incoming.left, right: incoming.right } }
  }, progress)
}
for (const viewport of [{ width: 1280, height: 720 }, { width: 390, height: 844 }, { width: 844, height: 390 }]) {
  test(`Café single-step roll and frame handoff at ${viewport.width}x${viewport.height}`, async ({ page }, info) => {
    await page.setViewportSize(viewport)
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    await page.goto('/e2e/fixtures/center-presentation.html')
    const group = page.locator('[data-focus-target-group="storefront:commercial-cafe-slot:baseline"]')
    const track = group.locator('[data-storefront-label-phase]')
    const large = group.locator('[data-focus-frame-group="storefront:commercial-cafe-slot:baseline"]')
    const small = group.locator('[data-focus-frame-group="door:street-cafe-entry"]')
    await expect(large).toHaveAttribute('data-focus-frame-phase', 'visible')
    const bounds = await group.evaluate(element => {
      const slot = element.querySelector('[data-storefront-label-slot]')!.getBoundingClientRect()
      const range = document.createRange(); range.selectNodeContents(element.querySelector('.scene-mainline-storefront__label-text')!)
      const text = range.getBoundingClientRect()
      return { left: text.left - slot.left, right: slot.right - text.right, width: text.width, frameWidth: element.querySelector('[data-focus-frame-group="storefront:commercial-cafe-slot:baseline"]')!.getBoundingClientRect().width }
    })
    expect(bounds.left).toBeGreaterThanOrEqual(0)
    expect(bounds.right).toBeGreaterThanOrEqual(0)
    expect(bounds.frameWidth - bounds.width).toBeCloseTo(6, 0)
    await page.screenshot({ path: info.outputPath('baseline.png') })
    await page.locator('[data-fixture-approach]').click()
    await expect(track).toHaveAttribute('data-storefront-label-phase', 'retracting')
    await expect(small).toHaveAttribute('data-focus-frame-phase', 'collapsed')
    await expect(track).toHaveAttribute('data-storefront-label-phase', 'revealing')
    await expect(large).toHaveAttribute('data-focus-frame-phase', 'collapsed')
    const samples = []
    for (const progress of [0, .25, .5, .75, .99]) {
      const sample = await sampleRoll(track, progress)
      expect(sample.duration).toBe(700)
      expect(sample.incoming.right).toBeCloseTo(sample.old.left, 1)
      samples.push(sample)
      await page.screenshot({ path: info.outputPath(`reveal-${progress}.png`) })
    }
    expect(samples[3].old.left).toBeGreaterThan(samples[1].old.left)
    await track.evaluate(element => element.getAnimations().forEach(animation => animation.finish()))
    await expect(track).toHaveAttribute('data-storefront-label-phase', 'revealed')
    await expect(small).toHaveAttribute('data-focus-frame-phase', 'visible')
    await page.locator('[data-fixture-approach]').click()
    await expect(track).toHaveAttribute('data-storefront-label-phase', 'lingering')
    await expect(small).toHaveAttribute('data-focus-frame-phase', 'retracting')
    await page.locator('[data-fixture-approach]').click()
    await expect(track).toHaveAttribute('data-storefront-label-phase', 'revealed')
    await expect(small).toHaveAttribute('data-focus-frame-phase', 'visible')
    await page.locator('[data-fixture-approach]').click()
    await expect(track).toHaveAttribute('data-storefront-label-phase', 'restoring', { timeout: 5000 })
    await expect(small).toHaveAttribute('data-focus-frame-phase', 'collapsed')
    await expect(large).toHaveAttribute('data-focus-frame-phase', 'collapsed')
    for (const progress of [0, .25, .5, .75, .99]) {
      const sample = await sampleRoll(track, progress)
      expect(sample.duration).toBe(700)
      expect(sample.incoming.right).toBeCloseTo(sample.old.left, 1)
      await page.screenshot({ path: info.outputPath(`restore-${progress}.png`) })
    }
    await track.evaluate(element => element.getAnimations().forEach(animation => animation.finish()))
    await expect(track).toHaveAttribute('data-storefront-label-phase', 'baseline')
    await expect(large).toHaveAttribute('data-focus-frame-phase', 'visible')
    expect(errors).toEqual([])
  })
}
test('Café reduced motion retains the three-second grace', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/e2e/fixtures/center-presentation.html')
  const track = page.locator('[data-storefront-label-slot][data-storefront-id="commercial-cafe-slot"] [data-storefront-label-phase]')
  await page.locator('[data-fixture-approach]').click()
  await expect(track).toHaveAttribute('data-storefront-label-phase', 'revealed')
  await page.locator('[data-fixture-approach]').click()
  await expect(track).toHaveAttribute('data-storefront-label-phase', 'lingering')
  await page.waitForTimeout(1000)
  await expect(track).toHaveAttribute('data-storefront-label-phase', 'lingering')
  await page.locator('[data-fixture-approach]').click()
  await expect(track).toHaveAttribute('data-storefront-label-phase', 'revealed')
})

test('leaving during reveal and re-entering during restore consume the current motion', async ({ page }) => {
  await page.goto('/e2e/fixtures/center-presentation.html')
  const track = page.locator('[data-storefront-label-slot][data-storefront-id="commercial-cafe-slot"] [data-storefront-label-phase]')
  const approach = page.locator('[data-fixture-approach]')
  await approach.click()
  await expect(track).toHaveAttribute('data-storefront-label-phase', 'revealing')
  await sampleRoll(track, .5)
  await approach.click()
  await expect(track).toHaveAttribute('data-storefront-label-phase', 'revealing')
  await track.evaluate(element => element.getAnimations().forEach(animation => animation.finish()))
  await expect(track).toHaveAttribute('data-storefront-label-phase', 'lingering')
  await approach.click()
  await expect(track).toHaveAttribute('data-storefront-label-phase', 'revealed')
  await approach.click()
  await expect(track).toHaveAttribute('data-storefront-label-phase', 'restoring')
  await sampleRoll(track, .5)
  await approach.click()
  await expect(track).toHaveAttribute('data-storefront-label-phase', 'revealing')
  await expect(track).toHaveAttribute('data-storefront-label-phase', 'revealed')
  await expect(page.locator('[data-focus-frame-group="door:street-cafe-entry"]')).toHaveAttribute('data-focus-frame-phase', 'visible')
})
