import { expect, test } from '@playwright/test'

test('door mechanism opens and closes with no glyph or frame completion events', async ({ page }) => {
  await page.clock.install()
  await page.goto('/e2e/fixtures/passage-clock.html')
  await expect(page.locator('[data-phase]')).toHaveText('closed')
  await page.locator('[data-request]').click()
  await expect(page.locator('[data-phase]')).toHaveText('opening')
  await expect(page.locator('[data-passable]')).toHaveText('false')
  await page.clock.runFor(240)
  await expect(page.locator('[data-phase]')).toHaveText('open')
  await expect(page.locator('[data-passable]')).toHaveText('true')
  await page.locator('[data-release]').click()
  await expect(page.locator('[data-phase]')).toHaveText('holding')
  await page.clock.runFor(500)
  await expect(page.locator('[data-phase]')).toHaveText('closing')
  await page.locator('[data-request]').click()
  await expect(page.locator('[data-phase]')).toHaveText('open')
  await page.clock.runFor(300)
  await expect(page.locator('[data-passable]')).toHaveText('true')
  await page.locator('[data-release]').click()
  await page.clock.runFor(740)
  await expect(page.locator('[data-phase]')).toHaveText('closed')
  await expect(page.locator('[data-passable]')).toHaveText('false')
})
