import { registerPhoneTestNetwork } from './phoneTestNetwork'
registerPhoneTestNetwork()
import { expect, test, type Page, type TestInfo } from '@playwright/test'
import { mkdir } from 'node:fs/promises'
import { join } from 'node:path'
async function capture(page:Page, info:TestInfo, name:string) {
 const directory=process.env.PHONE_SCREENSHOT_DIR
 if(directory)await mkdir(directory,{recursive:true})
 await expect(page.locator('.world-phone')).toHaveAttribute('data-phone-phase','open')
 await page.locator('.world-phone__app-view').evaluateAll(elements=>Promise.all(elements.flatMap(e=>e.getAnimations().map(a=>a.finished.catch(()=>{})))))
 await page.screenshot({path:directory?join(directory,`${info.title.split(' ')[0]}-${name}.png`):info.outputPath(`${name}.png`)})
}
async function seed(page:Page,device:'inner'|'surface'='inner') {
 await page.route('**/rest/v1/analytics_events**',route=>route.fulfill({status:201,body:''}))
 await page.route('**/rest/v1/center_feedback_submissions**',route=>route.fulfill({status:201,body:''}))
 await page.addInitScript(device=>{
  localStorage.setItem('newtone-public-release-cutover-v1','center-v1')
  if(!localStorage.getItem('newtone-player-save-v1'))localStorage.setItem('newtone-player-save-v1',JSON.stringify({currentSceneId:'commercial-cafe',phoneDevice:device,sceneState:{'commercial-cafe':{commercialCafeStoryStatus:'complete'}},updatedAt:100}))
 },device)
}
for(const viewport of [{width:1440,height:900},{width:390,height:844}]) {
 test(`${viewport.width} Phone correction full cross-app and screenshot matrix`,async({page},info)=>{
  test.setTimeout(90000)
  await page.setViewportSize(viewport)
  await seed(page)
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await page.goto('/?scene=commercial-cafe')
  await page.getByLabel('打开手机').click()
  const phone=page.locator('.world-phone')
  await expect(phone.locator('.world-phone__close')).toHaveCount(0)
  await expect(phone.locator('.world-phone__apps [data-app=notes]')).toHaveCount(0)
  await expect(phone.locator('.world-phone__home-indicator')).toHaveCount(0)
  await expect(phone.locator('[aria-current=date]')).toHaveText('12')
  await expect(phone.locator('.world-phone__calendar-grid span')).toHaveCount(31)
  await capture(page,info,'home-calendar-pin')
  await phone.locator('.world-phone__pin-candidates button').click()
  await expect(phone.locator('.world-phone__pin-candidates button')).toHaveAttribute('aria-pressed','true')
  await phone.locator('.world-phone__memo-open').click()
  await capture(page,info,'notes-list')
  await phone.getByRole('button',{name:'新增备忘',exact:true}).click()
  await capture(page,info,'notes-add')
  await phone.getByLabel('新备忘标题').fill('询问老周')
  await phone.getByLabel('新备忘内容').fill('记住永和小馆的营业时间')
  await phone.getByRole('button',{name:'保存备忘'}).click()
  await expect(phone.locator('[data-note-kind=player]')).toContainText('询问老周')
  await phone.getByRole('button',{name:'历史记录',exact:true}).click()
  await capture(page,info,'notes-history')
  await phone.locator('.world-phone__timeline summary').first().click()
  await expect(phone.locator('.world-phone__timeline details[open] p')).toBeVisible()
  await capture(page,info,'notes-history-expanded')
  await phone.getByLabel('返回手机主屏').click()
  await phone.locator('[data-app=contacts]').click()
  await expect(phone.locator('.world-phone__contact-row')).toHaveCount(1)
  await expect(phone).not.toContainText('若雨')
  await phone.locator('.world-phone__contact-row').click()
  await capture(page,info,'contact-detail')
  await phone.getByLabel('联系人备注').fill('在咖啡馆见过')
  await phone.getByLabel('联系人备注').blur()
  await phone.getByRole('button',{name:'电话',exact:true}).click()
  await capture(page,info,'contact-call')
  await phone.getByRole('button',{name:'挂断',exact:true}).click()
  await phone.getByRole('button',{name:'信息',exact:true}).click()
  await capture(page,info,'messages')
  await phone.getByLabel('展开永和小馆地点卡').click()
  await capture(page,info,'location-card')
  await phone.getByRole('button',{name:'永和小馆',exact:true}).click()
  await expect(phone.locator('[data-map-world=inner]')).toHaveAttribute('data-map-zoom','1.650')
  const detail=phone.getByRole('region',{name:'永和小馆地点详情'})
  await expect(detail).not.toContainText('简介')
  await expect(detail).toContainText('营业时间'); await expect(detail).not.toContainText('营业中')
  await capture(page,info,'map-yonghe')
  await detail.getByRole('button',{name:'查看全部营业时间'}).click()
  await expect(detail).toContainText('06:00–08:00')
  await expect(detail).toContainText('11:00–13:00')
  await expect(detail).toContainText('17:00–20:00')
  await capture(page,info,'map-hours')
  await detail.getByRole('button',{name:'叫车前往',exact:true}).scrollIntoViewIfNeeded(); await expect(detail.getByRole('button',{name:'叫车前往',exact:true})).toBeInViewport()
  await expect(detail.locator('.world-phone__weekly-hours dt')).toHaveCount(7)
  const sheetSize=await detail.evaluate(e=>({height:(e as HTMLElement).offsetHeight,limit:(e.closest('.world-phone__app-content') as HTMLElement).clientHeight*.6}))
  expect(sheetSize.height).toBeLessThanOrEqual(Math.ceil(sheetSize.limit))
  await phone.locator('.world-phone__map-viewport').click({position:{x:15,y:45}}); await expect(phone.locator('.world-phone__map-detail')).toHaveCount(0)
  await phone.getByLabel('回到地图概览').click()
  await capture(page,info,'map-default')
  for(const [id] of [['commercial','商业街'],['zhongshuyuan','中枢院'],['mine','矿区']]) {
   await phone.getByLabel('回到地图概览').click()
   await phone.locator(`[data-map-region=${id}]`).click()
   await capture(page,info,`map-${id}`)
   if(id==='zhongshuyuan') {
    await phone.getByRole('button',{name:'电话 0000'}).click()
    await expect(phone.getByRole('region',{name:'正在呼叫中枢院 · 0000'})).toBeVisible()
    await capture(page,info,'place-call')
    await phone.getByRole('button',{name:'挂断',exact:true}).click()
   }
   await phone.locator('.world-phone__map-viewport').click({position:{x:15,y:45}}); await expect(phone.locator('.world-phone__map-detail')).toHaveCount(0)
  }
  await phone.getByLabel('回到地图概览').click()
  await phone.locator('[data-map-region=zhongshuyuan]').click()
  await phone.getByRole('button',{name:'叫车前往',exact:true}).click()
  await expect(phone.getByText('正在打开叫车…',{exact:true})).toHaveCount(0)
  await expect(phone.getByRole('heading',{name:'前往中枢院'})).toBeVisible()
  await capture(page,info,'ride-vehicles')
  await phone.getByRole('button',{name:'更换目的地'}).click()
  await capture(page,info,'ride-destinations')
  await phone.getByLabel('展开叫车面板').click()
  await expect(phone.locator('.world-phone__ride-sheet')).toHaveAttribute('data-expanded','true')
  await phone.getByLabel('收起叫车面板').click()
  await expect(phone.locator('.world-phone__ride-sheet')).toHaveAttribute('data-expanded','false')
  const grip=await phone.getByLabel('展开叫车面板').boundingBox()
  await page.mouse.move(grip!.x+grip!.width/2,grip!.y+grip!.height/2);await page.mouse.down()
  await page.mouse.move(grip!.x+grip!.width/2,grip!.y+grip!.height/2-40);await page.mouse.up()
  await expect(phone.locator('.world-phone__ride-sheet')).toHaveAttribute('data-expanded','true')
  await phone.getByLabel('收起叫车面板').click()
  await phone.getByRole('button',{name:/中枢院.*从当前位置出发/}).click()
  await phone.getByRole('button',{name:/^舒适型/}).click()
  await expect(phone.getByRole('button',{name:/^舒适型/})).toHaveAttribute('aria-pressed','true')
  await capture(page,info,'ride-selected')
  await phone.getByRole('button',{name:'确认叫车',exact:true}).click()
  await expect(phone.getByRole('button',{name:'正在叫车…'})).toBeVisible()
  await expect(phone.locator('[data-ride-order=true]')).toContainText('目的地')
  await capture(page,info,'ride-waiting')
  await phone.getByLabel('返回手机主屏').click()
  await phone.locator('[data-app=feedback]').click()
  await capture(page,info,'feedback-form')
  await phone.getByLabel('自定义反馈').fill('Phone v1 local mocked release validation')
  await phone.getByRole('button',{name:'提交反馈',exact:true}).click()
  await expect(phone.getByText('已收到，谢谢',{exact:true})).toBeVisible()
  await capture(page,info,'feedback-success')
  await page.keyboard.press('Escape')
  await expect(phone).toHaveAttribute('data-phone-phase','closed')
  expect(errors).toEqual([])
 })
}
test('Phone rectangle and outside dismissal consume input; Surface contacts and offline services stay readable',async({page},info)=>{
 await page.setViewportSize({width:390,height:844});await seed(page,'surface')
 await page.goto('/?scene=commercial-cafe');await page.getByLabel('打开手机').click()
 const phone=page.locator('.world-phone'),actor=page.locator('[data-actor-id=protagonist]')
 const position=await actor.getAttribute('style')
 await phone.locator('.world-phone__header').click()
 await expect(actor).toHaveAttribute('style',position!)
 await phone.locator('[data-app=contacts]').click()
 await expect(phone.getByText('暂无联系人',{exact:true})).toBeVisible()
 await expect(phone).not.toContainText('当前手机没有里世界联系人')
 await capture(page,info,'contacts-empty')
 await phone.getByLabel('返回手机主屏').click();await phone.locator('[data-app=map]').click()
 await capture(page,info,'offline-map')
 await phone.getByLabel('返回手机主屏').click();await phone.locator('[data-app=ride]').click()
 await expect(phone).toContainText('当前无网络');await capture(page,info,'offline-ride')
 await phone.getByLabel('返回手机主屏').click();await phone.locator('[data-app=feedback]').click()
 await page.route('**/rest/v1/center_feedback_submissions**',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({message:'offline validation'})}))
 await phone.getByLabel('自定义反馈').fill('Phone v1 offline validation')
 await phone.getByRole('button',{name:'提交反馈',exact:true}).click()
 await expect(phone.getByText('已收到，谢谢',{exact:true})).toHaveCount(0)
 await expect(phone.getByRole('button',{name:'提交反馈',exact:true})).toBeEnabled()
 await capture(page,info,'offline-feedback')
 await page.mouse.click(2,200)
 await expect(phone).toHaveAttribute('data-phone-phase','closed')
 await expect(actor).toHaveAttribute('style',position!)
 await expect(actor).not.toHaveClass(/is-moving/)
})
