import { registerPhoneTestNetwork } from './phoneTestNetwork'
registerPhoneTestNetwork()
import { expect, test, type Page, type TestInfo } from '@playwright/test'
import { join } from 'node:path'

async function seed(page: Page) {
  await page.addInitScript(() => {
    localStorage.setItem('newtone-public-release-cutover-v1', 'center-v1')
    if (!localStorage.getItem('newtone-player-save-v1')) localStorage.setItem('newtone-player-save-v1', JSON.stringify({ currentSceneId: 'commercial-cafe', phoneDevice: 'inner', sceneState: { 'commercial-cafe': { commercialCafeStoryStatus: 'complete' } }, updatedAt: 100 }))
  })
  await page.goto('/?scene=commercial-cafe')
}
async function capture(page: Page, info: TestInfo, name: string) {
  await page.locator('.world-phone').evaluate(e => Promise.all(e.getAnimations({ subtree: true }).filter(a => Number(a.effect?.getComputedTiming().iterations) !== Infinity).map(a => a.finished.catch(() => {}))))
  await page.screenshot({ path: process.env.PHONE_SCREENSHOT_DIR ? join(process.env.PHONE_SCREENSHOT_DIR, `${info.title.split(' ')[0]}-round2-${name}.png`) : info.outputPath(`${name}.png`) })
}
for (const viewport of [{ width: 1440, height: 900 }, { width: 390, height: 844 }]) {
  test(`${viewport.width} capsule, continuous map, floating details and stable trip estimates`, async ({ page }, info) => {
    await page.setViewportSize(viewport); await seed(page)
    const phone = page.locator('.world-phone'), actor = page.locator('[data-actor-id=protagonist]')
    await expect(phone).toHaveAttribute('data-phone-phase', 'closed')
    const handle = await phone.getByLabel('打开手机').boundingBox()
    expect(handle!.height).toBeGreaterThanOrEqual(44)
    expect(await phone.locator('.world-phone__handle-mark').evaluate(e => e.getBoundingClientRect().height)).toBe(10)
    await capture(page, info, 'capsule')
    await phone.getByLabel('打开手机').click()
    await expect(phone.locator('[aria-current=date]')).toHaveText('12')
    const todayColumn = await phone.locator('[aria-current=date]').evaluate(e => Array.from(e.parentElement!.children).filter(c => c.tagName === 'SPAN').indexOf(e) % 7)
    expect(todayColumn).toBe(5)
    const rain = phone.locator('[data-weather=rainy]'), sun = phone.locator('[data-weather=sunny]')
    expect(await rain.first().evaluate(e => getComputedStyle(e, '::before').animationName)).toBe('phone-calendar-rain')
    expect(await sun.first().evaluate(e => getComputedStyle(e, '::before').animationName)).toBe('phone-calendar-sun')
    expect(await rain.first().evaluate(e => getComputedStyle(e).overflow)).toBe('hidden')
    await phone.locator('[data-app=map]').click()
    const map = phone.locator('.world-phone__map'), canvas = phone.locator('.world-phone__map-viewport')
    await expect(map).toHaveAttribute('data-map-zoom', '1.000')
    await expect(phone.locator('[data-map-poi]')).toHaveCount(0)
    await expect(map.locator('[data-map-transit]')).toHaveCount(3)
    const before = await canvas.evaluate(e => e.clientHeight)
    await phone.locator('[data-map-region=commercial]').click()
    const detail = phone.getByRole('region', { name: '商业街地点详情' })
    await expect(detail).toBeVisible()
    expect(await canvas.evaluate(e => e.clientHeight)).toBe(before)
    await expect(detail).toContainText('营业时间')
    await expect(detail).not.toContainText(/营业中|休息中|开始营业|结束营业/)
    await detail.getByText('查看全部营业时间', { exact: true }).click()
    await expect(detail.locator('dt')).toHaveText(['周一','周二','周三','周四','周五','周六','周日'])
    await expect(detail.locator('dd')).toHaveText(Array(7).fill('10:00–22:00'))
    await expect(detail.getByText('查看全部营业时间', { exact: true })).toHaveCount(0)
    await capture(page, info, 'sheet-hours')
    const style = await map.getAttribute('style')
    await canvas.click({ position: { x: 15, y: 45 } })
    await expect(phone.locator('.world-phone__map-detail')).toHaveCount(0)
    await expect(map).toHaveAttribute('style', style!)
    await phone.getByLabel('回到地图概览').click()
    await phone.getByLabel('放大地图').click(); await phone.getByLabel('放大地图').click()
    await expect(map).toHaveAttribute('data-map-zoom', '1.563')
    await expect(phone.locator('[data-map-poi]')).toHaveCount(3)
    await canvas.hover({ position: { x: 30, y: 100 } }); await page.mouse.wheel(0, -17)
    await expect.poll(async () => Number(await map.getAttribute('data-map-zoom'))).toBeGreaterThan(1.6)
    expect(await phone.locator('.world-phone__map-marker span').first().evaluate(e => getComputedStyle(e).fontSize)).toBe('12px')
    await phone.getByLabel('回到地图概览').click()
    await capture(page, info, 'map-overview')
    await phone.locator('[data-map-region=zhongshuyuan]').click()
    const start = Date.now()
    await phone.getByText('叫车前往', { exact: true }).click()
    await expect(phone.getByRole('heading', { name: '前往中枢院' })).toBeVisible()
    expect(Date.now() - start).toBeLessThan(900)
    await expect(phone.locator('[data-trip-minutes]')).toHaveAttribute('data-trip-minutes', '12')
    await expect(phone.locator('[data-trip-minutes]')).toContainText('预计 12:12 左右到达')
    const estimate = await phone.locator('[data-trip-minutes]').textContent()
    await phone.getByRole('button', { name: /^商务型/ }).click()
    await expect(phone.locator('[data-trip-minutes]')).toHaveText(estimate!)
    await capture(page, info, 'ride-estimates')
    await phone.getByRole('button',{name:'更换目的地',exact:true}).click()
    await phone.getByRole('button', { name: /矿区.*从当前位置出发/ }).click()
    await expect(phone.locator('[data-trip-minutes]')).toHaveAttribute('data-trip-minutes', '18')
    await expect(phone.locator('[data-trip-minutes]')).toContainText('12:18')
    const actorStyle = await actor.getAttribute('style')
    await phone.locator('.world-phone__header').click()
    await phone.locator('.world-phone__map-viewport').hover({ position: { x: 30, y: 100 } }); await page.mouse.wheel(0, -400)
    await expect(actor).toHaveAttribute('style', actorStyle!)
    await page.keyboard.press('Escape'); await expect(phone).toHaveAttribute('data-phone-phase', 'closed')
    await phone.getByLabel('打开手机').click(); await expect(phone).toHaveAttribute('data-phone-phase', 'open')
    await page.mouse.click(2, 100); await expect(phone).toHaveAttribute('data-phone-phase', 'closed')
    await expect(actor).toHaveAttribute('style', actorStyle!)
  })
}
test('Reduced Motion and repeated navigation complete without a stuck animation', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' }); await seed(page)
  const phone = page.locator('.world-phone')
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  await page.getByLabel('打开手机').click()
  expect(await phone.locator('[data-weather=rainy]').first().evaluate(e => getComputedStyle(e, '::before').animationName)).toBe('none')
  for (const app of ['map','contacts','ride','contacts']) {
    await phone.locator(`[data-app=${app}]`).click()
    await expect(phone.locator(`[data-app-view=${app}]`)).toBeVisible()
    await phone.getByLabel('返回手机主屏').dblclick()
    await expect(phone.getByLabel('剧情日历')).toBeVisible()
  }
  await phone.locator('[data-app=contacts]').click(); await phone.locator('.world-phone__contact-row').click()
  await phone.getByRole('button', { name: '信息', exact: true }).click()
  await expect(phone.getByRole('region', { name: '与老周的短信' })).toBeVisible()
  await phone.getByLabel('返回联系人').click()
  await expect(phone.getByRole('region', { name: '老周联系人详情' })).toBeVisible()
  await phone.getByLabel('返回联系人').click()
  await expect(phone.locator('.world-phone__contact-row')).toHaveCount(1)
  await expect(phone).not.toContainText('若雨')
  expect(errors).toEqual([])
})
test('real driver deadline only signals capsule, persists unread and opens notification on demand', async ({ page }, info) => {
  await page.setViewportSize({ width: 390, height: 844 }); await seed(page)
  const phone = page.locator('.world-phone')
  await page.getByLabel('打开手机').click(); await phone.locator('[data-app=ride]').click()
  await phone.getByRole('button', { name: /中枢院.*从当前位置出发/ }).click()
  await phone.getByRole('button', { name: /^快车/ }).click()
  await phone.getByRole('button', { name: '确认叫车', exact: true }).click()
  await expect(phone.locator('[data-ride-order=true]')).toContainText('司机正在路上')
  await capture(page, info, 'driver-distance')
  await page.keyboard.press('Escape'); await expect(phone).toHaveAttribute('data-phone-phase', 'closed')
  await expect(phone.locator('.world-phone__notification-dot')).toBeVisible({ timeout: 30000 })
  await expect(phone).toHaveAttribute('data-phone-phase', 'closed')
  await expect(page.locator('.world-phone__dismiss-region')).toHaveCount(0)
  await expect(phone.locator('.world-phone__notification-flow')).toHaveCount(0)
  await capture(page, info, 'driver-capsule')
  await page.getByLabel('打开手机').click()
  await expect(phone.getByLabel('手机通知')).toContainText('司机已到达')
  await phone.locator('.world-phone__lock-hint').click()
  await expect(phone.locator('[data-app=ride]')).toHaveAttribute('data-unread', 'true')
  await page.reload(); await page.getByLabel('打开手机').click()
  await expect(phone.getByLabel('手机通知')).toContainText('司机已到达')
  await phone.locator('[data-notification-app=ride]').click()
  await expect(phone.locator('[data-ride-order=true]')).toContainText('司机已到达')
  await phone.getByLabel('放大地图').click(); await phone.getByLabel('放大地图').click()
  const sizes = await phone.locator('.world-phone__map-marker span').evaluateAll(elements => elements.map(e => parseFloat(getComputedStyle(e).fontSize)))
  expect(sizes.every(size => size >= 11 && size <= 12)).toBe(true)
  await capture(page, info, 'waiting-map-zoom')
  await phone.getByLabel('返回手机主屏').click()
  await expect(phone.locator('[data-app=ride]')).toHaveAttribute('data-unread', 'false')
  await page.keyboard.press('Escape'); await expect(phone.locator('.world-phone__notification-dot')).toHaveCount(0)
})
